version: '3'

services:

  todotests:
    image: todotests
    depends_on:
      - 'todofront'
      - 'todoback'
    environment:
      - FRONT_HOST: frontend

  todofront:
    image: todofrontend
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - 'todoback'
    environment:
      - REACT_APP_API_HOST: backend    

  todoback:
    image: todobackend
    restart: always
    ports:
      - 3001:3001

